site_frontend:
    resource: "@SiteFrontendBundle/Controller"
    type:     annotation
    prefix:   /

sonata_user:
    resource: '@ApplicationSonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin